data_path: ../mlpf/solved_opf_ppcs_case30_10k

max_samples: 3000

random_seed: 123

validation_split: 0.33

defaults:
  - model: linear
  - _self_ # https://hydra.cc/docs/1.2/upgrades/1.0_to_1.1/default_composition_order/